version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${database}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${user} -d ${database}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    environment:
      user: ${user}
      password: ${password}
      host: db
      port: 5432
      database: ${database}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && pnpm ts-node src/db/create.ts && pnpm ts-node src/db/seed.ts && pnpm run start"

volumes:
  postgres_data:
